### PR TITLE
Add decipher as a user

### PR DESCRIPTION
**Pull request by joshua-rutherford**

### CODE REVIEW

**Comment by richarddli** [comment]
Thanks for the PR. In general, I think for the homepage we're pretty full on logos and not adding every company that uses Envoy at this point. Happy to discuss though of others @caniszczyk or @mattklein123 have differing views.

**Comment by joshua-rutherford** [comment]
Thanks for the response.  We understand that Envoy is now used by many companies and keeping them on the homepage would be onerous.  As a bit of insight, our company uses Envoy internally but  also leverages it within our product which is listed in the appropriate section of the site.  So technically, we are listed already but just wanted to maximize our exposure (naturally).

If you have a set of criteria for making the homepage that would be really helpful to us and others I am sure.  If it is just closed for submissions permanently now, that's okay too.

**Comment by mattklein123** [comment]
> If you have a set of criteria for making the homepage that would be really helpful to us and others I am sure. If it is just closed for submissions permanently now, that's okay too.

I agree at this point we need to have some better criteria on how/when a logo gets added to the home page. Frankly, the company needs to be "generally recognizable" at this point, but I'm not sure how to quantify that. @caniszczyk can you help here?

**Comment by richarddli** [comment]
For starters, I think a rationale for why Envoy Proxy would benefit from adding the logo to the homepage would help. 

"So technically, we are listed already but just wanted to maximize our exposure (naturally)." -- is a good rationale for Decipher, not so clear about Envoy ;-).

**Comment by richarddli** [comment]
@caniszczyk any comments on this? See also #102

**Comment by mattklein123** [comment]
Going to close this out. We will figure out a more official policy.

**Pull request closed without merging**
