### PR TITLE
fix #77

### LINKED ISSUE #77: Remove Turbine Labs as a company offering support

### PR DESCRIPTION
**Pull request by phoenixking25**
removed turbine-labs details from `home.yml`

### CODE REVIEW

**Comment by lucperkins** [comment]
@phoenixking25 LGTM. Approved pending DCO signature (feel free to force push).

**Comment by phoenixking25** [comment]
@lucperkins i dont have write access!

**Comment by phoenixking25** [comment]
@lucperkins done

**Comment by lucperkins** [comment]
Thanks a lot!

**Pull request merged**
