### PR TITLE
Add missing try links

### PR DESCRIPTION
**Pull request by pgherveou**
This should fix https://github.com/envoyproxy/envoyproxy.github.io/issues/141

### CODE REVIEW

**Comment by pgherveou** [comment]
using the preview link
https://deploy-preview-151--teacher-glances-63085.netlify.app/try/debugging-envoy-proxy
https://deploy-preview-151--teacher-glances-63085.netlify.app/try/load-balancing

**Comment by pgherveou** [comment]
pulling it locally to ` --signoff` my commits...

**Comment by mattklein123** [comment]
cc @lucperkins would you mind taking a look?

**Comment by lucperkins** [comment]
LGTM

**Pull request merged**
