### PR TITLE
Add Atlassian logo to 'Used By' section on the main page

### PR DESCRIPTION
**Pull request by cetanu**
Hi folks,

Happy to put our logo on the site to show our support :)

Envoy is working magic for us so far and all the support via github and slack have been amazing.

Also I noticed in #114 that perhaps this won't be merged until a policy has been made for adding logos. Feel free to close this and notify me at a more appropriate time.

### CODE REVIEW

**Comment by mattklein123** [comment]
@caniszczyk can you please help us define a formalized logo policy? Thank you!

**Comment by mattklein123** [comment]
Awesome thanks @caniszczyk

**Comment by agrawroh** [comment]
@caniszczyk @cetanu 
Thanks for helping with the logo policy draft. Are there any updates on this yet?

**Comment by caniszczyk** [comment]
Amye has a draft here, let me get her to review it with @mattklein123 and I... and we will get it done.

**Comment by cetanu** [comment]
I'm not part of CNCF @agrawroh :)

**Comment by agrawroh** [comment]
> Amye has a draft here, let me get her to review it with @mattklein123 and I... and we will get it done. Sorry and thanks for your patience!

Sorry to be so persistent here. Do we have a policy yet?

**Comment by mattklein123** [comment]
I would like to see this happen also. @caniszczyk @amye any updates?

**Comment by mattklein123** [comment]
PTAL at the new guidelines here and reopen your PR if you would still like to put your logo up. Thank you! https://github.com/envoyproxy/envoyproxy.github.io/pull/142

**Pull request closed without merging**
