### PR TITLE
Add Gojek to list of companies using envoy

### PR DESCRIPTION
**Pull request by kevinbheda**
I work at Gojek and we are using envoy in production. Would be glad if you accept this pull request. 
Thanks

### CODE REVIEW

**Comment by mattklein123** [comment]
Awesome! @sipplified do you mind reviewing?

**Comment by richarddli** [comment]
@kevinbheda thanks! we're actually adding the logos in alpha order now ... do you mind doing that?

**Comment by kevinbheda** [comment]
@richarddli  sure will do it and update the PR, thanks!

**Comment by kevinbheda** [comment]
@richarddli  done added  Gojek in alpha order

**Pull request merged**
